import React, { useMemo } from "react";
import { marked } from "marked";
import DOMPurify from "dompurify";
import katex from "katex";

interface MarkdownRendererProps {
  content: string;
  className?: string;
}

/**
 * Pre-processes math expressions to prevent marked from mangling LaTeX backslashes,
 * underscores, asterisks, and braces, then renders KaTeX equations and integrates with marked.
 */
function renderMarkdownWithMath(content: string): string {
  if (!content) return "";

  // Helper to sanitize common LLM LaTeX mistakes (such as unescaped & inside formulas)
  const sanitizeLatex = (math: string): string => {
    return math.trim().replace(/(?<!\\)&/g, "\\&");
  };

  const mathBlocks: string[] = [];
  const mathInlines: string[] = [];

  // 1. Extract Display Math: $$ ... $$
  let processed = content.replace(/\$\$([\s\S]+?)\$\$/g, (_match, math) => {
    const cleanMath = sanitizeLatex(math);
    try {
      const rendered = katex.renderToString(cleanMath, {
        displayMode: true,
        throwOnError: false,
        errorColor: "#f59e0b",
      });
      const id = `KATEXBLOCK${mathBlocks.length}KATEX`;
      mathBlocks.push(rendered);
      return id;
    } catch {
      return _match;
    }
  });

  // Extract Display Math: \[ ... \]
  processed = processed.replace(/\\\[([\s\S]+?)\\\]/g, (_match, math) => {
    const cleanMath = sanitizeLatex(math);
    try {
      const rendered = katex.renderToString(cleanMath, {
        displayMode: true,
        throwOnError: false,
        errorColor: "#f59e0b",
      });
      const id = `KATEXBLOCK${mathBlocks.length}KATEX`;
      mathBlocks.push(rendered);
      return id;
    } catch {
      return _match;
    }
  });

  // 2. Extract Inline Math: $ ... $
  processed = processed.replace(/(?<!\$)\$(?!\$)([^\$\n\r]+?)(?<!\$)\$(?!\$)/g, (_match, math) => {
    // Avoid currency numbers like $50 or $100
    if (/^\s*\d+([.,]\d+)?\s*$/.test(math)) {
      return _match;
    }
    const cleanMath = sanitizeLatex(math);
    try {
      const rendered = katex.renderToString(cleanMath, {
        displayMode: false,
        throwOnError: false,
        errorColor: "#f59e0b",
      });
      const id = `KATEXINLINE${mathInlines.length}KATEX`;
      mathInlines.push(rendered);
      return id;
    } catch {
      return _match;
    }
  });

  // Extract Inline Math: \( ... \)
  processed = processed.replace(/\\\(([\s\S]+?)\\\)/g, (_match, math) => {
    const cleanMath = sanitizeLatex(math);
    try {
      const rendered = katex.renderToString(cleanMath, {
        displayMode: false,
        throwOnError: false,
        errorColor: "#f59e0b",
      });
      const id = `KATEXINLINE${mathInlines.length}KATEX`;
      mathInlines.push(rendered);
      return id;
    } catch {
      return _match;
    }
  });

  // 3. Parse Markdown with marked
  let html = marked.parse(processed, {
    async: false,
    gfm: true,
    breaks: true,
  }) as string;

  // 4. Re-inject KaTeX Display Blocks
  mathBlocks.forEach((rendered, i) => {
    const id = `KATEXBLOCK${i}KATEX`;
    const wrappedHtml = `<div class="katex-display-wrapper my-3 overflow-x-auto py-2.5 px-3 rounded-xl bg-stone-950/80 border border-stone-850 shadow-inner text-amber-200 text-center">${rendered}</div>`;
    const pRegex = new RegExp(`<p>\\s*${id}\\s*<\\/p>`, "g");
    html = html.replace(pRegex, wrappedHtml);
    html = html.replaceAll(id, wrappedHtml);
  });

  // 5. Re-inject KaTeX Inline Blocks
  mathInlines.forEach((rendered, i) => {
    const id = `KATEXINLINE${i}KATEX`;
    html = html.replaceAll(id, `<span class="katex-inline-wrapper px-1 text-amber-300">${rendered}</span>`);
  });

  return html;
}

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({
  content,
  className = "",
}) => {
  const sanitizedHtml = useMemo(() => {
    if (!content) return "";

    const rawHtml = renderMarkdownWithMath(content);

    // Sanitize the HTML for secure rendering while allowing MathML and SVGs generated by KaTeX
    if (typeof window !== "undefined") {
      return DOMPurify.sanitize(rawHtml, {
        USE_PROFILES: { html: true, mathMl: true, svg: true },
        ADD_TAGS: [
          "annotation",
          "semantics",
          "math",
          "mrow",
          "mi",
          "mo",
          "mn",
          "msup",
          "msub",
          "mfrac",
          "mtext",
          "mspace",
          "mtable",
          "mtr",
          "mtd",
        ],
        ADD_ATTR: [
          "target",
          "rel",
          "aria-hidden",
          "style",
          "viewBox",
          "xmlns",
          "d",
          "height",
          "width",
          "encoding",
        ],
      });
    }
    return rawHtml;
  }, [content]);

  return (
    <div
      className={`jauhari-markdown text-stone-300 leading-relaxed text-xs sm:text-sm ${className}`}
      dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
    />
  );
};
